import os
import json
import pandas as pd

BREEDS_CSV = './model_assets/breeds.csv'
WRITE_FILE_PATH = '../src/assets'

# NOTE: asterisk (*) indicates abbreviated name
NAME_MAP = {
    'affenpinscher': 'Affenpinscher',
    'afghan_hound': 'Afghan Hound',
    'african_hunting_dog': 'African Hunting Dog',
    'airedale': 'Airedale',
    'american_staffordshire_terrier': 'American Staffordshire *',
    'appenzeller': 'Appenzeller',
    'australian_terrier': 'Australian Terrier',
    'basenji': 'Basenji',
    'basset': 'Basset',
    'beagle': 'Beagle',
    'bedlington_terrier': 'Bedlington Terrier',
    'bernese_mountain_dog': 'Bernese Mountain Dog',
    'black-and-tan_coonhound': 'Black-and-Tan Coonhound',
    'blenheim_spaniel': 'Blenheim Spaniel',
    'bloodhound': 'Bloodhound',
    'bluetick': 'Bluetick',
    'border_collie': 'Border Collie',
    'border_terrier': 'Border Terrier',
    'borzoi': 'Borzoi',
    'boston_bull': 'Boston Bull',
    'bouvier_des_flandres': 'Bouvier des Flandres',
    'boxer': 'Boxer',
    'brabancon_griffon': 'Brabancon Griffon',
    'briard': 'Briard',
    'brittany_spaniel': 'Brittany Spaniel',
    'bull_mastiff': 'Bull Mastiff',
    'cairn': 'Cairn',
    'cardigan': 'Cardigan',
    'chesapeake_bay_retriever': 'Chesapeake Bay Retriever',
    'chihuahua': 'Chihuahua',
    'chow': 'Chow',
    'clumber': 'Clumber',
    'cocker_spaniel': 'Cocker Spaniel',
    'collie': 'Collie',
    'curly-coated_retriever': 'Curly-Coated Retriever',
    'dandie_dinmont': 'Dandie Dinmont',
    'dhole': 'Dhole',
    'dingo': 'Dingo',
    'doberman': 'Doberman',
    'english_foxhound': 'English Foxhound',
    'english_setter': 'English Setter',
    'english_springer': 'English Springer',
    'entlebucher': 'Entlebucher',
    'eskimo_dog': 'Eskimo Dog',
    'flat-coated_retriever': 'Flat-Coated Retriever',
    'french_bulldog': 'French Bulldog',
    'german_shepherd': 'German Shepherd',
    'german_short-haired_pointer': 'Short-Haired Pointer *',
    'giant_schnauzer': 'Giant Schnauzer',
    'golden_retriever': 'Golden Retriever',
    'gordon_setter': 'Gordon Setter',
    'great_dane': 'Great Dane',
    'great_pyrenees': 'Great Pyrenees',
    'greater_swiss_mountain_dog': 'Swiss Mountain Dog *',
    'groenendael': 'Groenendael',
    'ibizan_hound': 'Ibizan Hound',
    'irish_setter': 'Irish Setter',
    'irish_terrier': 'Irish Terrier',
    'irish_water_spaniel': 'Irish Water Spaniel',
    'irish_wolfhound': 'Irish Wolfhound',
    'italian_greyhound': 'Italian Greyhound',
    'japanese_spaniel': 'Japanese Spaniel',
    'keeshond': 'Keeshond',
    'kelpie': 'Kelpie',
    'kerry_blue_terrier': 'Kerry Blue Terrier',
    'komondor': 'Komondor',
    'kuvasz': 'Kuvasz',
    'labrador_retriever': 'Labrador Retriever',
    'lakeland_terrier': 'Lakeland Terrier',
    'leonberg': 'Leonberg',
    'lhasa': 'Lhasa',
    'malamute': 'Malamute',
    'malinois': 'Malinois',
    'maltese_dog': 'Maltese Dog',
    'mexican_hairless': 'Mexican Hairless',
    'miniature_pinscher': 'Miniature Pinscher',
    'miniature_poodle': 'Miniature Poodle',
    'miniature_schnauzer': 'Miniature Schnauzer',
    'newfoundland': 'Newfoundland',
    'norfolk_terrier': 'Norfolk Terrier',
    'norwegian_elkhound': 'Norwegian Elkhound',
    'norwich_terrier': 'Norwich Terrier',
    'old_english_sheepdog': 'Old English Sheepdog',
    'otterhound': 'Otterhound',
    'papillon': 'Papillon',
    'pekinese': 'Pekinese',
    'pembroke': 'Pembroke',
    'pomeranian': 'Pomeranian',
    'pug': 'Pug',
    'redbone': 'Redbone',
    'rhodesian_ridgeback': 'Rhodesian Ridgeback',
    'rottweiler': 'Rottweiler',
    'saint_bernard': 'Saint_bernard',
    'saluki': 'Saluki',
    'samoyed': 'Samoyed',
    'schipperke': 'Schipperke',
    'scotch_terrier': 'Scotch Terrier',
    'scottish_deerhound': 'Scottish Deerhound',
    'sealyham_terrier': 'Sealyham Terrier',
    'shetland_sheepdog': 'Shetland Sheepdog',
    'shih-tzu': 'Shih-Tzu',
    'siberian_husky': 'Siberian Husky',
    'silky_terrier': 'Silky Terrier',
    'soft-coated_wheaten_terrier': 'Wheaten Terrier *',
    'staffordshire_bullterrier': 'Staffordshire Bullterrier',
    'standard_poodle': 'Standard Poodle',
    'standard_schnauzer': 'Standard Schnauzer',
    'sussex_spaniel': 'Sussex Spaniel',
    'tibetan_mastiff': 'Tibetan Mastiff',
    'tibetan_terrier': 'Tibetan Terrier',
    'toy_poodle': 'Toy Poodle',
    'toy_terrier': 'Toy Terrier',
    'vizsla': 'Vizsla',
    'walker_hound': 'Walker Hound',
    'weimaraner': 'Weimaraner',
    'welsh_springer_spaniel': 'Welsh Springer Spaniel',
    'west_highland_white_terrier': 'West Highland Terrier *',
    'whippet': 'Whippet',
    'wire-haired_fox_terrier': 'Wire-Haired Fox Terrier',
    'yorkshire_terrier': 'Yorkshire Terrier'
}


if __name__ == '__main__':

    df = pd.read_csv(BREEDS_CSV)

    dog_breeds = {}
    for index, row in df.iterrows():
        dog_breeds[str(row.breed)] = {
            'id': int(row.id),
            'name': NAME_MAP[str(row.breed)],
            'photo_path': '/dog_breeds/' + str(row.breed) + '.jpg'
        }

    with open(os.path.join(WRITE_FILE_PATH, 'dog_breeds.json'), 'w') as json_file:
        dog_breeds_json = json.dump(dog_breeds, json_file, sort_keys=True)
